name: images
on:
  push:
jobs:
  render-images:
    name: render-images
    runs-on: ubuntu-latest
    container: linalinn/pcbdraw:kicad7
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: make image directory
        run: mkdir $GITHUB_WORKSPACE/images && mkdir $GITHUB_WORKSPACE/images/front $GITHUB_WORKSPACE/images/back

      - name: Run pcbdraw render front
        continue-on-error: true
        run: pcbdraw render m2sdr.kicad_pcb images/front.png --side front --timeout-by-factor 4 --debug-print --debug-path $GITHUB_WORKSPACE/images/front

      - name: Run pcbdraw render back
        continue-on-error: true
        run: pcbdraw render m2sdr.kicad_pcb images/back.png --side back --timeout-by-factor 4 --debug-print --debug-path $GITHUB_WORKSPACE/images/back

      - name: Setup Pages
        if: github.ref == 'refs/heads/master'
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v1
        with:
          path: "images"

  deploy-pages:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: render-images
    
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2